[[permission]]
identifier = "allow-app-commands"
description = "Enables all gmpublisher custom commands."
commands.allow = [
  "check_dir",
  "check_file",
  "open",
  "open_file_location",
  "file_size",
  "reloaded",
  "js_error",
  "error",
  "info",
  "warn",
  "websocket",
  "cancel_transaction",
  "update_settings",
  "validate_gmod",
  "window_resized",
  "browse_installed_addons",
  "get_installed_addon",
  "downloader_extract_gmas",
  "is_steam_connected",
  "get_current_user",
  "get_steam_user",
  "fetch_workshop_items",
  "fetch_workshop_item",
  "browse_my_workshop",
  "workshop_item_channel",
  "workshop_download",
  "verify_whitelist",
  "publish",
  "verify_icon",
  "publish_icon",
  "browse_subscribed_addons",
  "addon_size_analyzer",
  "get_content_generator_manifests",
  "update_content_generator_manifest",
  "preview_gma",
  "extract_preview_entry",
  "extract_preview_gma",
  "extract_gma",
  "search",
  "search_channel",
  "full_search",
]
